name: keralarescue
description: Kerala rescue provides alerts of announcements being made in keralarescue.in 
author: Ganesh S P <ganesh.sp006@gmail.com>
homepage: https://github.com/ganeshsp1
version: 1.0.0+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.11+2
  cupertino_icons: ^0.1.2
  # firebase_database: ^3.0.5
  firebase_messaging: ^5.1.3
  http: any
  url_launcher: ^5.1.2
  groovin_widgets: 1.4.2
  shimmer: 1.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/social-care.png"

flutter:
  assets:
    - assets/icon/
    - assets/images/kerala.PNG
    - assets/images/keralarescue.jpg
  uses-material-design: true